### ISSUE TITLE
Bing (网页版, GPT-4) Failed to fetch

### ISSUE THREAD

**Issue by SeasonPilot** [josStorer/chatGPTBox#212]
**Describe the bug**
**问题描述**

https://cn.bing.com/turing/conversation/create
<img width="245" alt="image" src="https://user-images.githubusercontent.com/61238101/231750254-2a36f35d-a6bd-4089-8b3c-fdd5947b0f66.png">
Failed to fetch
302

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]  mac
 - Browser: [e.g. chrome, safari]  chrome
 - Extension Version: [e.g. v2.0.2]

**Additional context**
**其他**

**Comment by josStorer** [comment]
是否配置了代理, 国内不可直连

**Comment by SeasonPilot** [comment]
> 是否配置了代理, 国内不可直连

时好时坏，有时候可以访问。

**Comment by josStorer** [comment]
可以通过部署 https://github.com/waylaidwanderer/node-chatgpt-api 进行代理

并切换api模式

![image](https://user-images.githubusercontent.com/13366013/231762712-b12e5199-6a34-4a8e-8906-6ef80f5e76f7.png)

**Comment by SeasonPilot** [comment]
> 可以通过部署 https://github.com/waylaidwanderer/node-chatgpt-api 进行代理
> 
> 并切换api模式
> 
> ![image](https://user-images.githubusercontent.com/13366013/231762712-b12e5199-6a34-4a8e-8906-6ef80f5e76f7.png)

使用 node-chatgpt-api 的反向代理功能吗？
https://github.com/waylaidwanderer/node-chatgpt-api#using-a-reverse-proxy

**Comment by SeasonPilot** [comment]
> https://github.com/waylaidwanderer/node-chatgpt-api#api-server
> 
> 用这个仓库的代码起一个服务器, 然后在它的设置中使用你的代理地址

报错：
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:14152:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BingAIClient.createNewConversation (file:///usr/local/lib/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:70:26)
    at async BingAIClient.sendMessage (file:///usr/local/lib/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:177:51)
    at async Object.<anonymous> (file:///usr/local/lib/node_modules/@waylaidwanderer/chatgpt-api/bin/server.js:105:18) {
  cause: Error: Request was cancelled.
      at makeNetworkError (node:internal/deps/undici/undici:6714:35)
      at makeAppropriateNetworkError (node:internal/deps/undici/undici:6769:120)
      at httpNetworkFetch (node:internal/deps/undici/undici:13961:18)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async httpNetworkOrCacheFetch (node:internal/deps/undici/undici:13856:33)
      at async httpFetch (node:internal/deps/undici/undici:13705:37)
      at async schemeFetch (node:internal/deps/undici/undici:13633:18)
      at async node:internal/deps/undici/undici:13509:20
      at async mainFetch (node:internal/deps/undici/undici:13505:20) {
    [cause]: undefined
  }
}
```


我填写的 settings.js

```
    bingAiClient: {
        // Necessary for some people in different countries, e.g. China (https://cn.bing.com)
        host: '',
        // The "_U" cookie value from bing.com
        userToken: '',
        // If the above doesn't work, provide all your cookies as a string instead
        cookies: '',
        // A proxy string like "http://<ip>:<port>"
        proxy: 'https://gog-mgiurl-jva-procton-1a.p.railway.app/',
        // (Optional) Set to true to enable `console.debug()` logging
        debug: false,
    },
    ```

**Comment by josStorer** [comment]
你填的这个地址是已经搭建好了bing的反代吗

**Comment by SeasonPilot** [comment]
> 



> 你填的这个地址是已经搭建好了bing的反代吗

我没有搭建反代，仅仅运行了 https://github.com/waylaidwanderer/node-chatgpt-api#api-server

这个仓库的代码起一个服务器, 然后填写了以上设置

**Comment by josStorer** [comment]
proxy: 'https://gog-mgiurl-jva-procton-1a.p.railway.app/', 要填你自己的本地梯子地址
比如 http://127.0.0.1:10809

**Comment by SeasonPilot** [comment]
> proxy: 'https://gog-mgiurl-jva-procton-1a.p.railway.app/', 要填你自己的本地梯子地址 比如 http://127.0.0.1:10809

我以为可以用 cloudflare
有可以使用 cloudflare 进行代理的方法吗？

**Comment by josStorer** [comment]
那应该属于反代搭建, 目前好像没有bing的
