### ISSUE TITLE
Bing (web version, GPT-4) returned an error

### ISSUE THREAD

**Issue by SeasonPilot** [josStorer/chatGPTBox#519]
**Describe the bug**
**问题描述**

Bing (web version, GPT-4) returned an error

**To Reproduce**
**如何复现**

**Expected behavior**
**期望行为**

**Screenshots**
**截图说明**

![image](https://github.com/josStorer/chatGPTBox/assets/61238101/cd026d6e-0704-49ff-b0da-b23a561e343e)
![image](https://github.com/josStorer/chatGPTBox/assets/61238101/8fd995b5-468f-4e88-ad35-16b331fb22de)

**Please complete the following information):**
**请补全以下内容**
 - OS:  mac
 - Browser: edge
 - Extension Version: 2.4.1 (最新)

**Additional context**
**其他**

**Comment by dengwanc** [comment]
same get this error:
```
Uncaught (in promise) Success: null
    at e.<anonymous> (chrome-extension://enjmfilpkbbabhgeoadmdpjjpnahkogf/content-script.js:2:616672)
    at m (chrome-extension://enjmfilpkbbabhgeoadmdpjjpnahkogf/shared.js:2:771693)
    at Generator.<anonymous> (chrome-extension://enjmfilpkbbabhgeoadmdpjjpnahkogf/shared.js:2:773030)
    at Generator.next (chrome-extension://enjmfilpkbbabhgeoadmdpjjpnahkogf/shared.js:2:772056)
    at i (chrome-extension://enjmfilpkbbabhgeoadmdpjjpnahkogf/shared.js:2:779827)
    at o (chrome-extension://enjmfilpkbbabhgeoadmdpjjpnahkogf/shared.js:2:780030)
```

**Comment by MG-Osman** [comment]
Can confirm i also get the same issues listed above when using bing.

**Comment by josStorer** [comment]
https://github.com/waylaidwanderer/node-chatgpt-api/pull/481
https://github.com/waylaidwanderer/node-chatgpt-api/issues/470

**Comment by josStorer** [comment]
should have been fixed in https://github.com/josStorer/chatGPTBox/commit/d639d29d6b50d32c8de9bd9c04a728db5cd9e919
